annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Sync argo-rollouts with upstream v1.7.2 plus security fixes
      links:
        - name: GitHub Release
          url: https://github.com/codefresh-io/argo-rollouts/releases/tag/v1.7.2-cap-CR-26082
  artifacthub.io/signKey: |
    fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
    url: https://argoproj.github.io/argo-helm/pgp_keys.asc
apiVersion: v2
appVersion: v1.7.2-cap-CR-26082
description: A Helm chart for Argo Rollouts
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-rollouts/assets/logo.png
keywords:
- argoproj
- argo-rollouts
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-rollouts
sources:
- https://github.com/argoproj/argo-rollouts
version: 2.37.3-2-v1.7.2-cap-CR-26082
