{{/* This service account is created as a way of providing an admin token to garage API, using automatic Kubernetes token generation mechanism for service accounts*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage-admin
  labels:
    {{- include "garage.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: garage-admin
  annotations:
    kubernetes.io/service-account.name: garage-admin
type: kubernetes.io/service-account-token
