{{- define "cf-argocd-extras.event-reporter.rbac" }}

  {{- $context := deepCopy . }}
  {{- $_ := set $context "Values" (mergeOverwrite dict .Values.global .Values.eventReporter) }}

  {{- if $context.Values.enabled }}
    {{- $templateName := printf "cf-common-%s.rbac" (index .Subcharts "cf-common").Chart.Version -}}
    {{- include $templateName $context -}}
  {{- end }}

{{- end }}

