apiVersion: v2
appVersion: 0.1.69-0
description: A Helm chart for Codefresh gitops runtime
name: gitops-runtime
version: 0.0.0
home: https://github.com/codefresh-io/gitops-runtime-helm
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
keywords:
  - codefresh
  - gitops
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
annotations:
  artifacthub.io/alternativeName: "codefresh-gitops-runtime"
dependencies:
- name: argo-cd
  repository: file://./charts/argo-cd
  condition: argo-cd.enabled
  version: 7.8.23-1-cap-v2.14.9-2025-04-20-584fc7f3
- name: argo-events
  repository: file://./charts/argo-events
  version: 2.4.7-1-cap-CR-28072
- name: argo-workflows
  repository: file://./charts/argo-workflows
  version: 0.45.2-v3.6.4-cap-CR-27392
  condition: argo-workflows.enabled
- name: argo-rollouts
  repository: file://./charts/argo-rollouts
  version: 2.37.3-2-v1.7.2-cap-CR-26082
  condition: argo-rollouts.enabled
- name: sealed-secrets
  repository: file://./charts/sealed-secrets
  version: 2.17.0
- name: codefresh-tunnel-client
  repository: file://./charts/codefresh-tunnel-client
  version: 0.1.19
  alias: tunnel-client
  condition: tunnel-client.enabled
- name: codefresh-gitops-operator
  repository:  file://./charts/codefresh-gitops-operator
  version: 0.5.4
  alias: gitops-operator
  condition: gitops-operator.enabled
- name: garage
  repository: file://./charts/garage
  alias: garage-workflows-artifact-storage
  version: 0.5.0-cf.3
  condition: garage-workflows-artifact-storage.enabled
- name: cf-argocd-extras
  repository: file://./charts/cf-argocd-extras
  version: 0.3.15
