{{- define "gitops-operator.resources.notifications-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.argoCdNotifications.secret.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "gitops-operator.labels" . | nindent 4 }}
type: Opaque
{{- end }}
