
{{- define "gitops-operator.resources.notifications_rbac" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: codefresh-gitops-operator-notifications
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get
  - list
  - update
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: codefresh-gitops-operator-notifications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codefresh-gitops-operator-notifications
subjects:
- kind: ServiceAccount
  name: {{ include "gitops-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
