{{- define "cf-argocd-extras.sources-server.rbac" }}

  {{- $context := deepCopy . }}
  {{- $_ := set $context "Values" (mergeOverwrite dict .Values.global .Values.sourcesServer) }}

  {{- $templateName := printf "cf-common-%s.rbac" (index .Subcharts "cf-common").Chart.Version -}}
  {{- include $templateName $context -}}

{{- end }}

