{{- define "cf-argocd-extras.sources-server.service" }}

{{- $context := deepCopy . }}
{{- $_ := set $context "Values" (mergeOverwrite dict .Values.global .Values.sourcesServer) }}

{{- $templateName := printf "cf-common-%s.service" (index .Subcharts "cf-common").Chart.Version -}}
{{- include $templateName $context -}}

{{- end }}

