{{/*
Some environment variables are determined by values provided in other components,
to keep the separation of components as pseudo library charts, they are defined here to be merged when components are generated.
*/}}
{{- define "gitops-operator.resources.environment-variables.calculated" }}
CF_URL: {{ .Values.global.codefresh.url }}
GITOPS_OPERATOR_VERSION: {{ .Chart.AppVersion }}
RUNTIME: {{ .Values.global.runtime.name }}
WEBHOOK_BIND_ADDRESS: :{{ .Values.argoCdNotifications.service.port }}
ARGO_CD_TOKEN_SECRET_NAME: argocd-token
ARGO_CD_TOKEN_SECRET_KEY: token
{{- end }}

{{- define "gitops-operator.resources.environment-variables.defaults" -}}
AP_URL: http://cap-app-proxy:3017
ARGO_CD_URL: argo-cd-server:80
ARGO_WF_URL: http://argo-server:2746
  {{/* if custom certificates are provided */}}
  {{- if .Values.global.codefresh.tls.caCerts.secretKeyRef }}
CF_CA_CERT: {{ printf "/app/config/codefresh-tls/%s" .Values.global.codefresh.tls.caCerts.secretKeyRef.key  }}
  {{- end }}
CF_TOKEN:
  valueFrom:
    secretKeyRef:
      name: codefresh-token
      key: token
HEALTH_PROBE_BIND_ADDRESS: :8081
LEADER_ELECT: true
METRICS_BIND_ADDRESS: 127.0.0.1:8080
RUNTIME_VERSION: 
  valueFrom:
    configMapKeyRef:
      name: codefresh-cm
      key: version
{{- end -}}
